// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package config

import (
	"github.com/google/wire"
	"stocks/app/controller"
	"stocks/app/repository"
	"stocks/app/service"
)

import (
	_ "github.com/joho/godotenv"
)

// Injectors from injector.go:

func Init() *Initialization {
	gormDB := ConnectToDB()
	stockRepositoryImpl := repository.StockRepositoryInit(gormDB)
	stockServiceImpl := service.StockServiceInit(stockRepositoryImpl)
	stockControllerImpl := controller.StockControllerInit(stockServiceImpl)
	initialization := NewInitialization(stockRepositoryImpl, stockServiceImpl, stockControllerImpl)
	return initialization
}

// injector.go:

var db = wire.NewSet(ConnectToDB)

var stockServiceSet = wire.NewSet(service.StockServiceInit, wire.Bind(new(service.StockService), new(*service.StockServiceImpl)))

var stockRepoSet = wire.NewSet(repository.StockRepositoryInit, wire.Bind(new(repository.StockRepository), new(*repository.StockRepositoryImpl)))

var stockCtrlSet = wire.NewSet(controller.StockControllerInit, wire.Bind(new(controller.StockController), new(*controller.StockControllerImpl)))
